DROP KEYSPACE gestionescolar;
CREATE KEYSPACE gestionescolar WITH REPLICATION = {'class':'SimpleStrategy', 'replication_factor':1};
use gestionescolar;


create table escuelas(
CLAVE VARCHAR PRIMARY KEY,
NOMBRE VARCHAR,
DIRECCION VARCHAR,
CIUDAD VARCHAR,
DOCENTES LIST<VARCHAR>,
ADMINISTRATIVOS LIST<VARCHAR>,
MANTENIMIENTO LIST<VARCHAR>,
ALUMNOS LIST<VARCHAR>
);

CREATE TABLE DOCENTES(
CURP VARCHAR PRIMARY KEY,
NOMBRE VARCHAR,
TELEFONO VARCHAR,
CUENTA VARCHAR,
NUMERO_OFICINA INT,
ESPECIALIDAD VARCHAR,
GRADO VARCHAR,
TUTORADOS LIST<VARCHAR>,
TUTORIAS_FIRMADAS BOOLEAN,
ESCUELA VARCHAR
);

CREATE TABLE ALUMNOS(
CURP VARCHAR PRIMARY KEY,
NOMBRE VARCHAR,
FECHA_NACIMIENTO VARCHAR,
TUTOR VARCHAR,
TUTORIA_FIRMADA BOOLEAN,
GRADO VARCHAR,
FECHA_INSCRIPCION VARCHAR,
ESCUELA VARCHAR
);

CREATE TABLE ADMINISTRATIVOS(
CURP VARCHAR PRIMARY KEY,
NOMBRE VARCHAR,
TELEFONO VARCHAR,
hora_entrada VARCHAR,
hora_salida VARCHAR,
CUENTA VARCHAR,
FUNCION VARCHAR,
EXTENSION VARCHAR,
CORREO VARCHAR,
ESCUELA VARCHAR
);

CREATE TABLE MANTENIMIENTO(
CURP VARCHAR PRIMARY KEY,
CUENTA VARCHAR,
NOMBRE VARCHAR,
TELEFONO VARCHAR,
TELEFONO_INSTITUCIONAL VARCHAR,
ESPECIALIDAD VARCHAR,
ESCUELA VARCHAR
);

CREATE TABLE alumnos_tutor(
TUTOR VARCHAR,
CURP VARCHAR,
NOMBRE VARCHAR,
FECHA_NACIMIENTO VARCHAR,
TUTORIA_FIRMADA BOOLEAN,
GRADO VARCHAR,
FECHA_INSCRIPCION VARCHAR,
ESCUELA VARCHAR,
PRIMARY KEY(TUTOR, CURP)
);

CREATE TABLE docentes_escuela(
ESCUELA VARCHAR,
CURP VARCHAR,
NOMBRE VARCHAR,
TELEFONO VARCHAR,
CUENTA VARCHAR,
NUMERO_OFICINA INT,
ESPECIALIDAD VARCHAR,
GRADO VARCHAR,
TUTORADOS LIST<VARCHAR>,
TUTORIAS_FIRMADAS BOOLEAN,
PRIMARY KEY(ESCUELA, CURP)
);

CREATE TABLE administrativos_escuela(
ESCUELA VARCHAR,
CURP VARCHAR,
NOMBRE VARCHAR,
TELEFONO VARCHAR,
hora_entrada VARCHAR,
hora_salida VARCHAR,
CUENTA VARCHAR,
FUNCION VARCHAR,
EXTENSION VARCHAR,
CORREO VARCHAR,
PRIMARY KEY(ESCUELA, CURP)
);